import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Movie({info}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>{info.title} - Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {info.title}
        </h1>
        <p>Nota: {info.vote_average}</p>

        <p>{info.overview}</p>

        <Image
          src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`}
          width={400}
          height={225}
          alt={`Plano de fundo do filme ${info.title}`}
        />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch(`https://nextjs-primeiros-passos.vercel.app/api/movie?id=${context.params.id}`)

  const { info } = await res.json()

  return {
    props: {
      info
    }
  }
}
