import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function About({author, github}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>About - Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre min
        </h1>
        <p>
          O sistema foi feito na live do Bonieky para demonstrar os primeiros passos com o framework Next.js.
        </p>
        <br />
        <Link href="https://www.youtube.com/watch?v=xjrDEZQ5LnA">
          <a className={styles.link}>
            Bonieky Lacerda - Primeiros Passos com Next.js
          </a>
        </Link>
        <br />
        <br />
        <Link href={github}>
          <a className={styles.link}>
            {author}
          </a>
        </Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      author: 'Leonardo Lima Coelho',
      github: 'https://github.com/Ryszol'
    }
  }
}
