import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Search() {
  const [searchText, setSearchText] = useState('')
  const [movieList, setMovieList] = useState([])

  const handleSearch = async () => {
    if (!searchText) return
    
    const res = await fetch(`https://nextjs-primeiros-passos.vercel.app/api/search?q=${searchText}`)
    const { list } = await res.json()

    setMovieList(list)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Buscar - Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Busca
        </h1>
        
        <input type="text" value={searchText} onChange={e => setSearchText(e.target.value)} />
        <button onClick={handleSearch}>Buscar</button>

{        <ul className={styles.grid}>
          {movieList.map(item => (
            <li key={item.id} className={styles.card}>
              <Link href={`/movie/${encodeURIComponent(item.id)}`}>
                <a>
                  <Image
                    src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                    alt={`Capa do filme ${item.title}`}
                    width="150"
                    height="225"
                  />
                  <br />
                  {item.title}
                </a>
              </Link>
            </li>
          ))}
        </ul>
}
      </main>
    </div>
  )
}
